name: ccpy-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - compilers
  - mkl
  - mkl-service
  - libblas=*=*mkl
  - bblas=*=*mkl
  - pkg-config
  - meson
  - meson-python
  - ninja
  - pandas
  - numpy
  - scipy
  - periodictable
  - pydantic
  - pip
  - setuptools
  - ipython
  - pyscf
  # Testing and lint
  - flake8
  - pytest
  - pytest-cov
