name: Docs

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:
    name: Build Docs
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: false
        python-version: 3.8
        environment-file: devtools/conda-envs/environment-dev.yaml

    - name: Environment Information
      shell: bash -l {0}
      run: |
        conda info
        conda list

    - name: Install Docs
      shell: bash -l {0}
      run: |
        conda install py-qcore breeze -c entos -c conda-forge
        qcore --accept-license
        pip install -r docs/requirements.txt

    - name: Install
      shell: bash -l {0}
      run: python -m pip install . --no-deps

    - name: Build Docs
      shell: bash -l {0}
      run: |
        make docs
